version: '3.9'

services:
  app:
    build: .
    container_name: task-management
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: task
      DATABASE_PASSWORD: password
      DATABASE_NAME: task_db
    env_file:
      - ./.env

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: task
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
